// flow-typed signature: 45ce34e80a7c1e97fdc8935dc353f2d0
// flow-typed version: <<STUB>>/babel-preset-rsuite_v0.0.1/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-preset-rsuite'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-preset-rsuite' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-preset-rsuite/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-preset-rsuite/lib/index.js' {
  declare module.exports: $Exports<'babel-preset-rsuite/lib/index'>;
}
