// flow-typed signature: 53d5bccabfb23f9a0e693009929cf2db
// flow-typed version: <<STUB>>/chartist_v^0.11.0/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'chartist'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'chartist' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'chartist/dist/chartist' {
  declare module.exports: any;
}

declare module 'chartist/dist/chartist.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'chartist/dist/chartist.js' {
  declare module.exports: $Exports<'chartist/dist/chartist'>;
}
declare module 'chartist/dist/chartist.min.js' {
  declare module.exports: $Exports<'chartist/dist/chartist.min'>;
}
