// flow-typed signature: fa4c216bac13f43c883622eb1f972783
// flow-typed version: <<STUB>>/child-process-promise_v^2.0.2/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'child-process-promise'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'child-process-promise' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'child-process-promise/lib-es5/ChildProcessError' {
  declare module.exports: any;
}

declare module 'child-process-promise/lib-es5/ChildProcessPromise' {
  declare module.exports: any;
}

declare module 'child-process-promise/lib-es5/index' {
  declare module.exports: any;
}

declare module 'child-process-promise/lib/ChildProcessError' {
  declare module.exports: any;
}

declare module 'child-process-promise/lib/ChildProcessPromise' {
  declare module.exports: any;
}

declare module 'child-process-promise/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'child-process-promise/index' {
  declare module.exports: $Exports<'child-process-promise'>;
}
declare module 'child-process-promise/index.js' {
  declare module.exports: $Exports<'child-process-promise'>;
}
declare module 'child-process-promise/lib-es5/ChildProcessError.js' {
  declare module.exports: $Exports<'child-process-promise/lib-es5/ChildProcessError'>;
}
declare module 'child-process-promise/lib-es5/ChildProcessPromise.js' {
  declare module.exports: $Exports<'child-process-promise/lib-es5/ChildProcessPromise'>;
}
declare module 'child-process-promise/lib-es5/index.js' {
  declare module.exports: $Exports<'child-process-promise/lib-es5/index'>;
}
declare module 'child-process-promise/lib/ChildProcessError.js' {
  declare module.exports: $Exports<'child-process-promise/lib/ChildProcessError'>;
}
declare module 'child-process-promise/lib/ChildProcessPromise.js' {
  declare module.exports: $Exports<'child-process-promise/lib/ChildProcessPromise'>;
}
declare module 'child-process-promise/lib/index.js' {
  declare module.exports: $Exports<'child-process-promise/lib/index'>;
}
