// flow-typed signature: b21d1d18f10e747a50dfd40c281733b2
// flow-typed version: <<STUB>>/svg-sprite-loader_v^3.7.1/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'svg-sprite-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'svg-sprite-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'svg-sprite-loader/examples/base-webpack.config' {
  declare module.exports: any;
}

declare module 'svg-sprite-loader/examples/browser-sprite-extract-mode/build/main' {
  declare module.exports: any;
}

declare module 'svg-sprite-loader/examples/browser-sprite-extract-mode/main' {
  declare module.exports: any;
}

declare module 'svg-sprite-loader/examples/browser-sprite-extract-mode/webpack.config' {
  declare module.exports: any;
}

declare module 'svg-sprite-loader/examples/browser-sprite-with-dll-extract-mode/build/dll' {
  declare module.exports: any;
}

declare module 'svg-sprite-loader/examples/browser-sprite-with-dll-extract-mode/build/main' {
  declare module.exports: any;
}

declare module 'svg-sprite-loader/examples/browser-sprite-with-dll-extract-mode/dll' {
  declare module.exports: any;
}

declare module 'svg-sprite-loader/examples/browser-sprite-with-dll-extract-mode/main' {
  declare module.exports: any;
}

declare module 'svg-sprite-loader/examples/browser-sprite-with-dll-extract-mode/webpack.config' {
  declare module.exports: any;
}

declare module 'svg-sprite-loader/examples/browser-sprite-with-dll-extract-mode/webpack.dll.config' {
  declare module.exports: any;
}

declare module 'svg-sprite-loader/examples/browser-sprite-with-dll/build/dll' {
  declare module.exports: any;
}

declare module 'svg-sprite-loader/examples/browser-sprite-with-dll/build/main' {
  declare module.exports: any;
}

declare module 'svg-sprite-loader/examples/browser-sprite-with-dll/dll' {
  declare module.exports: any;
}

declare module 'svg-sprite-loader/examples/browser-sprite-with-dll/main' {
  declare module.exports: any;
}

declare module 'svg-sprite-loader/examples/browser-sprite-with-dll/webpack.config' {
  declare module.exports: any;
}

declare module 'svg-sprite-loader/examples/browser-sprite-with-dll/webpack.dll.config' {
  declare module.exports: any;
}

declare module 'svg-sprite-loader/examples/browser-sprite/build/main' {
  declare module.exports: any;
}

declare module 'svg-sprite-loader/examples/browser-sprite/build/sprite' {
  declare module.exports: any;
}

declare module 'svg-sprite-loader/examples/browser-sprite/main' {
  declare module.exports: any;
}

declare module 'svg-sprite-loader/examples/browser-sprite/webpack.config' {
  declare module.exports: any;
}

declare module 'svg-sprite-loader/examples/custom-runtime-generator-extract-mode/build/main' {
  declare module.exports: any;
}

declare module 'svg-sprite-loader/examples/custom-runtime-generator-extract-mode/extracting-runtime-generator' {
  declare module.exports: any;
}

declare module 'svg-sprite-loader/examples/custom-runtime-generator-extract-mode/main' {
  declare module.exports: any;
}

declare module 'svg-sprite-loader/examples/custom-runtime-generator-extract-mode/webpack.config' {
  declare module.exports: any;
}

declare module 'svg-sprite-loader/examples/custom-runtime-generator/build/main' {
  declare module.exports: any;
}

declare module 'svg-sprite-loader/examples/custom-runtime-generator/icon' {
  declare module.exports: any;
}

declare module 'svg-sprite-loader/examples/custom-runtime-generator/main' {
  declare module.exports: any;
}

declare module 'svg-sprite-loader/examples/custom-runtime-generator/svg-to-icon-component-runtime-generator' {
  declare module.exports: any;
}

declare module 'svg-sprite-loader/examples/custom-runtime-generator/webpack.config' {
  declare module.exports: any;
}

declare module 'svg-sprite-loader/examples/extract-mode/build/main' {
  declare module.exports: any;
}

declare module 'svg-sprite-loader/examples/extract-mode/main' {
  declare module.exports: any;
}

declare module 'svg-sprite-loader/examples/extract-mode/webpack.config' {
  declare module.exports: any;
}

declare module 'svg-sprite-loader/examples/interop-with-html-webpack-plugin/build/main' {
  declare module.exports: any;
}

declare module 'svg-sprite-loader/examples/interop-with-html-webpack-plugin/main' {
  declare module.exports: any;
}

declare module 'svg-sprite-loader/examples/interop-with-html-webpack-plugin/webpack.config' {
  declare module.exports: any;
}

declare module 'svg-sprite-loader/examples/server-side-rendering/build/main' {
  declare module.exports: any;
}

declare module 'svg-sprite-loader/examples/server-side-rendering/main' {
  declare module.exports: any;
}

declare module 'svg-sprite-loader/examples/server-side-rendering/webpack.config' {
  declare module.exports: any;
}

declare module 'svg-sprite-loader/lib/config' {
  declare module.exports: any;
}

declare module 'svg-sprite-loader/lib/configurator' {
  declare module.exports: any;
}

declare module 'svg-sprite-loader/lib/exceptions' {
  declare module.exports: any;
}

declare module 'svg-sprite-loader/lib/loader' {
  declare module.exports: any;
}

declare module 'svg-sprite-loader/lib/plugin' {
  declare module.exports: any;
}

declare module 'svg-sprite-loader/lib/runtime-generator' {
  declare module.exports: any;
}

declare module 'svg-sprite-loader/lib/utils/generate-export' {
  declare module.exports: any;
}

declare module 'svg-sprite-loader/lib/utils/generate-import' {
  declare module.exports: any;
}

declare module 'svg-sprite-loader/lib/utils/generate-sprite-placeholder' {
  declare module.exports: any;
}

declare module 'svg-sprite-loader/lib/utils/get-all-modules' {
  declare module.exports: any;
}

declare module 'svg-sprite-loader/lib/utils/get-loader-options' {
  declare module.exports: any;
}

declare module 'svg-sprite-loader/lib/utils/get-loaders-rules' {
  declare module.exports: any;
}

declare module 'svg-sprite-loader/lib/utils/get-matched-rule' {
  declare module.exports: any;
}

declare module 'svg-sprite-loader/lib/utils/get-matched-rules' {
  declare module.exports: any;
}

declare module 'svg-sprite-loader/lib/utils/get-module-chunk' {
  declare module.exports: any;
}

declare module 'svg-sprite-loader/lib/utils/get-webpack-version' {
  declare module.exports: any;
}

declare module 'svg-sprite-loader/lib/utils/index' {
  declare module.exports: any;
}

declare module 'svg-sprite-loader/lib/utils/interpolate' {
  declare module.exports: any;
}

declare module 'svg-sprite-loader/lib/utils/is-module-should-be-extracted' {
  declare module.exports: any;
}

declare module 'svg-sprite-loader/lib/utils/is-webpack-1' {
  declare module.exports: any;
}

declare module 'svg-sprite-loader/lib/utils/mapped-list' {
  declare module.exports: any;
}

declare module 'svg-sprite-loader/lib/utils/normalize-rule' {
  declare module.exports: any;
}

declare module 'svg-sprite-loader/lib/utils/replace-in-module-source' {
  declare module.exports: any;
}

declare module 'svg-sprite-loader/lib/utils/replace-sprite-placeholder' {
  declare module.exports: any;
}

declare module 'svg-sprite-loader/lib/utils/stringify-symbol' {
  declare module.exports: any;
}

declare module 'svg-sprite-loader/lib/utils/stringify' {
  declare module.exports: any;
}

declare module 'svg-sprite-loader/plugin' {
  declare module.exports: any;
}

declare module 'svg-sprite-loader/runtime/browser-sprite.build' {
  declare module.exports: any;
}

declare module 'svg-sprite-loader/runtime/browser-sprite' {
  declare module.exports: any;
}

declare module 'svg-sprite-loader/runtime/sprite.build' {
  declare module.exports: any;
}

declare module 'svg-sprite-loader/runtime/sprite' {
  declare module.exports: any;
}

// Filename aliases
declare module 'svg-sprite-loader/examples/base-webpack.config.js' {
  declare module.exports: $Exports<'svg-sprite-loader/examples/base-webpack.config'>;
}
declare module 'svg-sprite-loader/examples/browser-sprite-extract-mode/build/main.js' {
  declare module.exports: $Exports<'svg-sprite-loader/examples/browser-sprite-extract-mode/build/main'>;
}
declare module 'svg-sprite-loader/examples/browser-sprite-extract-mode/main.js' {
  declare module.exports: $Exports<'svg-sprite-loader/examples/browser-sprite-extract-mode/main'>;
}
declare module 'svg-sprite-loader/examples/browser-sprite-extract-mode/webpack.config.js' {
  declare module.exports: $Exports<'svg-sprite-loader/examples/browser-sprite-extract-mode/webpack.config'>;
}
declare module 'svg-sprite-loader/examples/browser-sprite-with-dll-extract-mode/build/dll.js' {
  declare module.exports: $Exports<'svg-sprite-loader/examples/browser-sprite-with-dll-extract-mode/build/dll'>;
}
declare module 'svg-sprite-loader/examples/browser-sprite-with-dll-extract-mode/build/main.js' {
  declare module.exports: $Exports<'svg-sprite-loader/examples/browser-sprite-with-dll-extract-mode/build/main'>;
}
declare module 'svg-sprite-loader/examples/browser-sprite-with-dll-extract-mode/dll.js' {
  declare module.exports: $Exports<'svg-sprite-loader/examples/browser-sprite-with-dll-extract-mode/dll'>;
}
declare module 'svg-sprite-loader/examples/browser-sprite-with-dll-extract-mode/main.js' {
  declare module.exports: $Exports<'svg-sprite-loader/examples/browser-sprite-with-dll-extract-mode/main'>;
}
declare module 'svg-sprite-loader/examples/browser-sprite-with-dll-extract-mode/webpack.config.js' {
  declare module.exports: $Exports<'svg-sprite-loader/examples/browser-sprite-with-dll-extract-mode/webpack.config'>;
}
declare module 'svg-sprite-loader/examples/browser-sprite-with-dll-extract-mode/webpack.dll.config.js' {
  declare module.exports: $Exports<'svg-sprite-loader/examples/browser-sprite-with-dll-extract-mode/webpack.dll.config'>;
}
declare module 'svg-sprite-loader/examples/browser-sprite-with-dll/build/dll.js' {
  declare module.exports: $Exports<'svg-sprite-loader/examples/browser-sprite-with-dll/build/dll'>;
}
declare module 'svg-sprite-loader/examples/browser-sprite-with-dll/build/main.js' {
  declare module.exports: $Exports<'svg-sprite-loader/examples/browser-sprite-with-dll/build/main'>;
}
declare module 'svg-sprite-loader/examples/browser-sprite-with-dll/dll.js' {
  declare module.exports: $Exports<'svg-sprite-loader/examples/browser-sprite-with-dll/dll'>;
}
declare module 'svg-sprite-loader/examples/browser-sprite-with-dll/main.js' {
  declare module.exports: $Exports<'svg-sprite-loader/examples/browser-sprite-with-dll/main'>;
}
declare module 'svg-sprite-loader/examples/browser-sprite-with-dll/webpack.config.js' {
  declare module.exports: $Exports<'svg-sprite-loader/examples/browser-sprite-with-dll/webpack.config'>;
}
declare module 'svg-sprite-loader/examples/browser-sprite-with-dll/webpack.dll.config.js' {
  declare module.exports: $Exports<'svg-sprite-loader/examples/browser-sprite-with-dll/webpack.dll.config'>;
}
declare module 'svg-sprite-loader/examples/browser-sprite/build/main.js' {
  declare module.exports: $Exports<'svg-sprite-loader/examples/browser-sprite/build/main'>;
}
declare module 'svg-sprite-loader/examples/browser-sprite/build/sprite.js' {
  declare module.exports: $Exports<'svg-sprite-loader/examples/browser-sprite/build/sprite'>;
}
declare module 'svg-sprite-loader/examples/browser-sprite/main.js' {
  declare module.exports: $Exports<'svg-sprite-loader/examples/browser-sprite/main'>;
}
declare module 'svg-sprite-loader/examples/browser-sprite/webpack.config.js' {
  declare module.exports: $Exports<'svg-sprite-loader/examples/browser-sprite/webpack.config'>;
}
declare module 'svg-sprite-loader/examples/custom-runtime-generator-extract-mode/build/main.js' {
  declare module.exports: $Exports<'svg-sprite-loader/examples/custom-runtime-generator-extract-mode/build/main'>;
}
declare module 'svg-sprite-loader/examples/custom-runtime-generator-extract-mode/extracting-runtime-generator.js' {
  declare module.exports: $Exports<'svg-sprite-loader/examples/custom-runtime-generator-extract-mode/extracting-runtime-generator'>;
}
declare module 'svg-sprite-loader/examples/custom-runtime-generator-extract-mode/main.js' {
  declare module.exports: $Exports<'svg-sprite-loader/examples/custom-runtime-generator-extract-mode/main'>;
}
declare module 'svg-sprite-loader/examples/custom-runtime-generator-extract-mode/webpack.config.js' {
  declare module.exports: $Exports<'svg-sprite-loader/examples/custom-runtime-generator-extract-mode/webpack.config'>;
}
declare module 'svg-sprite-loader/examples/custom-runtime-generator/build/main.js' {
  declare module.exports: $Exports<'svg-sprite-loader/examples/custom-runtime-generator/build/main'>;
}
declare module 'svg-sprite-loader/examples/custom-runtime-generator/icon.jsx' {
  declare module.exports: $Exports<'svg-sprite-loader/examples/custom-runtime-generator/icon'>;
}
declare module 'svg-sprite-loader/examples/custom-runtime-generator/main.jsx' {
  declare module.exports: $Exports<'svg-sprite-loader/examples/custom-runtime-generator/main'>;
}
declare module 'svg-sprite-loader/examples/custom-runtime-generator/svg-to-icon-component-runtime-generator.js' {
  declare module.exports: $Exports<'svg-sprite-loader/examples/custom-runtime-generator/svg-to-icon-component-runtime-generator'>;
}
declare module 'svg-sprite-loader/examples/custom-runtime-generator/webpack.config.js' {
  declare module.exports: $Exports<'svg-sprite-loader/examples/custom-runtime-generator/webpack.config'>;
}
declare module 'svg-sprite-loader/examples/extract-mode/build/main.js' {
  declare module.exports: $Exports<'svg-sprite-loader/examples/extract-mode/build/main'>;
}
declare module 'svg-sprite-loader/examples/extract-mode/main.js' {
  declare module.exports: $Exports<'svg-sprite-loader/examples/extract-mode/main'>;
}
declare module 'svg-sprite-loader/examples/extract-mode/webpack.config.js' {
  declare module.exports: $Exports<'svg-sprite-loader/examples/extract-mode/webpack.config'>;
}
declare module 'svg-sprite-loader/examples/interop-with-html-webpack-plugin/build/main.js' {
  declare module.exports: $Exports<'svg-sprite-loader/examples/interop-with-html-webpack-plugin/build/main'>;
}
declare module 'svg-sprite-loader/examples/interop-with-html-webpack-plugin/main.js' {
  declare module.exports: $Exports<'svg-sprite-loader/examples/interop-with-html-webpack-plugin/main'>;
}
declare module 'svg-sprite-loader/examples/interop-with-html-webpack-plugin/webpack.config.js' {
  declare module.exports: $Exports<'svg-sprite-loader/examples/interop-with-html-webpack-plugin/webpack.config'>;
}
declare module 'svg-sprite-loader/examples/server-side-rendering/build/main.js' {
  declare module.exports: $Exports<'svg-sprite-loader/examples/server-side-rendering/build/main'>;
}
declare module 'svg-sprite-loader/examples/server-side-rendering/main.js' {
  declare module.exports: $Exports<'svg-sprite-loader/examples/server-side-rendering/main'>;
}
declare module 'svg-sprite-loader/examples/server-side-rendering/webpack.config.js' {
  declare module.exports: $Exports<'svg-sprite-loader/examples/server-side-rendering/webpack.config'>;
}
declare module 'svg-sprite-loader/lib/config.js' {
  declare module.exports: $Exports<'svg-sprite-loader/lib/config'>;
}
declare module 'svg-sprite-loader/lib/configurator.js' {
  declare module.exports: $Exports<'svg-sprite-loader/lib/configurator'>;
}
declare module 'svg-sprite-loader/lib/exceptions.js' {
  declare module.exports: $Exports<'svg-sprite-loader/lib/exceptions'>;
}
declare module 'svg-sprite-loader/lib/loader.js' {
  declare module.exports: $Exports<'svg-sprite-loader/lib/loader'>;
}
declare module 'svg-sprite-loader/lib/plugin.js' {
  declare module.exports: $Exports<'svg-sprite-loader/lib/plugin'>;
}
declare module 'svg-sprite-loader/lib/runtime-generator.js' {
  declare module.exports: $Exports<'svg-sprite-loader/lib/runtime-generator'>;
}
declare module 'svg-sprite-loader/lib/utils/generate-export.js' {
  declare module.exports: $Exports<'svg-sprite-loader/lib/utils/generate-export'>;
}
declare module 'svg-sprite-loader/lib/utils/generate-import.js' {
  declare module.exports: $Exports<'svg-sprite-loader/lib/utils/generate-import'>;
}
declare module 'svg-sprite-loader/lib/utils/generate-sprite-placeholder.js' {
  declare module.exports: $Exports<'svg-sprite-loader/lib/utils/generate-sprite-placeholder'>;
}
declare module 'svg-sprite-loader/lib/utils/get-all-modules.js' {
  declare module.exports: $Exports<'svg-sprite-loader/lib/utils/get-all-modules'>;
}
declare module 'svg-sprite-loader/lib/utils/get-loader-options.js' {
  declare module.exports: $Exports<'svg-sprite-loader/lib/utils/get-loader-options'>;
}
declare module 'svg-sprite-loader/lib/utils/get-loaders-rules.js' {
  declare module.exports: $Exports<'svg-sprite-loader/lib/utils/get-loaders-rules'>;
}
declare module 'svg-sprite-loader/lib/utils/get-matched-rule.js' {
  declare module.exports: $Exports<'svg-sprite-loader/lib/utils/get-matched-rule'>;
}
declare module 'svg-sprite-loader/lib/utils/get-matched-rules.js' {
  declare module.exports: $Exports<'svg-sprite-loader/lib/utils/get-matched-rules'>;
}
declare module 'svg-sprite-loader/lib/utils/get-module-chunk.js' {
  declare module.exports: $Exports<'svg-sprite-loader/lib/utils/get-module-chunk'>;
}
declare module 'svg-sprite-loader/lib/utils/get-webpack-version.js' {
  declare module.exports: $Exports<'svg-sprite-loader/lib/utils/get-webpack-version'>;
}
declare module 'svg-sprite-loader/lib/utils/index.js' {
  declare module.exports: $Exports<'svg-sprite-loader/lib/utils/index'>;
}
declare module 'svg-sprite-loader/lib/utils/interpolate.js' {
  declare module.exports: $Exports<'svg-sprite-loader/lib/utils/interpolate'>;
}
declare module 'svg-sprite-loader/lib/utils/is-module-should-be-extracted.js' {
  declare module.exports: $Exports<'svg-sprite-loader/lib/utils/is-module-should-be-extracted'>;
}
declare module 'svg-sprite-loader/lib/utils/is-webpack-1.js' {
  declare module.exports: $Exports<'svg-sprite-loader/lib/utils/is-webpack-1'>;
}
declare module 'svg-sprite-loader/lib/utils/mapped-list.js' {
  declare module.exports: $Exports<'svg-sprite-loader/lib/utils/mapped-list'>;
}
declare module 'svg-sprite-loader/lib/utils/normalize-rule.js' {
  declare module.exports: $Exports<'svg-sprite-loader/lib/utils/normalize-rule'>;
}
declare module 'svg-sprite-loader/lib/utils/replace-in-module-source.js' {
  declare module.exports: $Exports<'svg-sprite-loader/lib/utils/replace-in-module-source'>;
}
declare module 'svg-sprite-loader/lib/utils/replace-sprite-placeholder.js' {
  declare module.exports: $Exports<'svg-sprite-loader/lib/utils/replace-sprite-placeholder'>;
}
declare module 'svg-sprite-loader/lib/utils/stringify-symbol.js' {
  declare module.exports: $Exports<'svg-sprite-loader/lib/utils/stringify-symbol'>;
}
declare module 'svg-sprite-loader/lib/utils/stringify.js' {
  declare module.exports: $Exports<'svg-sprite-loader/lib/utils/stringify'>;
}
declare module 'svg-sprite-loader/plugin.js' {
  declare module.exports: $Exports<'svg-sprite-loader/plugin'>;
}
declare module 'svg-sprite-loader/runtime/browser-sprite.build.js' {
  declare module.exports: $Exports<'svg-sprite-loader/runtime/browser-sprite.build'>;
}
declare module 'svg-sprite-loader/runtime/browser-sprite.js' {
  declare module.exports: $Exports<'svg-sprite-loader/runtime/browser-sprite'>;
}
declare module 'svg-sprite-loader/runtime/sprite.build.js' {
  declare module.exports: $Exports<'svg-sprite-loader/runtime/sprite.build'>;
}
declare module 'svg-sprite-loader/runtime/sprite.js' {
  declare module.exports: $Exports<'svg-sprite-loader/runtime/sprite'>;
}
