// flow-typed signature: c518c9a261240c84d3af73d647e2bb5b
// flow-typed version: <<STUB>>/transform-loader_v^0.2.3/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'transform-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'transform-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'transform-loader/cacheable' {
  declare module.exports: any;
}

declare module 'transform-loader/test/test' {
  declare module.exports: any;
}

declare module 'transform-loader/test/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'transform-loader/cacheable.js' {
  declare module.exports: $Exports<'transform-loader/cacheable'>;
}
declare module 'transform-loader/index' {
  declare module.exports: $Exports<'transform-loader'>;
}
declare module 'transform-loader/index.js' {
  declare module.exports: $Exports<'transform-loader'>;
}
declare module 'transform-loader/test/test.js' {
  declare module.exports: $Exports<'transform-loader/test/test'>;
}
declare module 'transform-loader/test/webpack.config.js' {
  declare module.exports: $Exports<'transform-loader/test/webpack.config'>;
}
